### PR TITLE
Java 10 fix for HeapWalker.stringValue()

### PR DESCRIPTION
**Pull request by stefan-reich**
I think it works. Compatible with heap dumps from any Java version.

### CODE REVIEW

**Comment by aragozin** [comment]
I have enabled few autotest in build and make them not crash on Java 9.
I have also added few test case for String parsing and it is falling on non-Latin1 strings.
Could you make UTF16 encoded strings work too?

Tests are in master.

**Comment by stefan-reich** [comment]
I believe it works for UTF16 strings also.

**Comment by stefan-reich** [comment]
That's embarrassing. You're right, I didn't test that.

**Comment by stefan-reich** [comment]
Now it works :)

**Comment by aragozin** [comment]
Merged

**Pull request closed without merging**
